ecommerce_project/cart/urls.py
from django.urls import path
from . import views

app_name='cart'


urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),

]

ecommerce_project/ecommerce_app/urls.py
from django.urls import path
from . import views
app_name='ecommerce_app'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatdetail'),
]

ecommerce_project/ecommerce_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecommerce_app/',include('ecommerce_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce_project/search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),

]

ecommerce_project/cart/models.py
from django.db import models
from ecommerce_app.models import products

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model) :
    product=models.ForeignKey(products,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/ecommerce_app/models.py
from django.db import models
from django.urls import reverse

class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('ecommerce_app:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class products(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('ecommerce_app:prodCatdetail',args=[self.category.slug,self.slug])

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'


    def __str__(self):
        return '{}'.format(self.name)

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/cart/views.py
from ecommerce_app.models import products
from .models import CartItem,Cart
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

def add_cart(request,product_id):
    product=products.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),

    try:
        cart_Item=CartItem.objects.get(product=product,cart=cart)
        if cart_Item.quantity < cart_Item.product.stock:
          cart_Item.quantity += 1
        cart_Item.save()
    except CartItem.DoesNotExist:
        cart_Item=CartItem.objects.create(
          product=product,
            quantity=1,
            cart=cart
        )
        cart_Item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(products,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(products,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce_project/ecommerce_app/views.py
from django.shortcuts import render, get_object_or_404
from . models import category,products
from django.core.paginator import Paginator,EmptyPage,InvalidPage
def allProdCat(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        product_list=products.objects.all().filter(category=c_page,available=True)
    else:
        product_list=products.objects.all().filter(available=True)
    paginator=Paginator(product_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        product=paginator.page(page)
    except (EmptyPage,InvalidPage):
        product=paginator.page(paginator.num_pages)
    return render(request,"category.html",{'category':c_page,'products':product})
def proDetail(request,c_slug,product_slug):
    try:
        product=products.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e

    return render(request,'product.html',{'product':product})

ecommerce_project/search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import products
from django.db.models import Q

def SearchResult(request):
    product=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        product=products.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'product':product})

ecommerce_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fc51e437b8.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">

  <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
This is the cart page. proceed to review your items and place the order
{% endblock %}
{% block title %}
  Cart-Borcelle PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
     <div class="text-center">
      <br>
        <h1 class="text-center my_title">
          Your Shopping Cart is empty
        </h1>
         <br>
        <p class="text-center">
          Please Click <a href="{% url 'ecommerce_app:allProdCat' %}">Here</a>to continue purchase
        </p>
     </div>
</div>
{% else %}
<div>
     <div class="text-center">
     <br>
       <h1 class="text-center my_title">
         Your Shopping Cart
       </h1>
       <br>
     </div>
  <div class="row mx-auto">
     <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
     <table class="table my_custom_table">
        <thead class="my_custom_thead">
          <tr>
            <th colspan="5">
                your Items
            </th>
          </tr>
        </thead>
         <tbody>
         {% for cart_item in cart_items %}
    <tr>
        <td>
            <a href="{{ cart_item.product.get_absolute_url }}"><img src="{{ cart_item.product.image.url }}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
        </td>
        <td class="text-left">
            {{cart_item.product.name}}
            <br>
            SKU: {{cart_item.product.id}}
            <br>
            price: $ {{cart_item.product.price}}
            <br>
            Qty: {{ cart_item.quantity }} x ${{ cart_item}}
        </td>
        <td>
            $ {{ cart_item.sub_total }}
        </td>
        {% if cart_item.quantity < cart_item.product.stock %}
        <td>
        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a" >
        <i class="fas fa-plus custom_icon"></i>
        </a>&nbsp;
        <a href="/cart/remove/{{ cart_item.product.id }}/" class="custom_icon">
        <i class="fas fa-minus custom_icon"></i>
        </a>&nbsp;
        <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon">
            <i class="fa-solid fa-trash custom_icon"></i>
        </a>

       </td>

        {% else %}
            <td>
                <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-minus custom_icon" style="color: #0f0f10;"></i></a>
                <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash custom_icon" style="color: #0f0f10;"></i></a>
            </td>
        {% endif %}
    </tr>
{% endfor %}
         </tbody>
     </table>
     </div>
      <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
         <thead class="my_custom_thead">
          <tr>
              <th>
                  Checkout
              </th>
          </tr>
         </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping items before proceedind with the order payment.
                </td>
            </tr>
            <tr>
                <td class="text-center">
                    Your Total is : <strong>{{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
          <div class="mx-auto">
              <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
          </div>
      </div>
</div>
  {% endif %}
</div>
{% endblock %}

ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {% if category %}
      {{ category.description|truncatewords:155 }}
   {% else %}
       welcome to store where you can experience different tastes....
   {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -  Borcelle
    {% else %}
         see our new collections - Borcelle
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
      <div>
        <div class="row my_row_class">
            <div class="mx-auto">
            <p class="text-center custom_a" ><a href="{% url 'ecommerce_app:allProdCat' %}" class="custom_a" style="color:black;">Our product collections</a> </p>
        </div>
            </div>
      </div>
    {% endif %}
      <div class="mx_auto">
    {% if category %}
            <img class="my_image1" src="{{category.image.url}}" alt="{{category.name}}">
      </div>
      <br>
      <div>
             <h1 class="text-center my_title"><b>{{category.name}}</b></h1>
             <p class="text-center">{{category.description}}</p>
      </div>
    {% else %}
      <div>
           <img  class="my_image1 my_image_padding" src="{% static 'img/banner2.png' %}" alt="our products" width="100%" height="100px">
      </div>
      <br>
      <div>
         <h1 class="text-center my_title">Our products collections </h1>
         <p class="text-center">perfect balance of sweetness and a satisfying texture. Whether it's a classic chocolate cake, a decadent red velvet, or a fruity sponge, a delicious cake should leave you wanting more with every bite.</p>
      </div>
    {% endif %}
      <div class="container">
      <div class="row mx_auto">
        {% for product in products.object_list %}
           <div class="my_bottom_margin col-9 col-sm-4 col-md-4 xol-lg-4">
           <div class="card text-center"  style="min-width:18rem;">
             <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" style="width:400px;height:350px;margin-top:10px;" alt="{{product.name}}"></a>
           <div class="card-body">
             <h4>{{product.name}}</h4>
             <p>{{product.price}}</p>
           </div>
           </div>
           </div>
        {% endfor %}
      </div>
          <div class="mx-auto">
              {% if products.paginator.num_pages > 1 %}
              <hr>
              <div class="text-center">
                  {% for pg in products.paginator.page_range %}
                  <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
                  {% endfor %}
              </div>
              {% endif %}
          </div>
          <br>
      </div>
{% endblock %}

ecommerce_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Borcelle pvt ltd</p>
</div>

ecommerce_project/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerce_app:allProdCat' %}">   <img src="{% static 'img/logo1.png' %}" alt="logimage" width="150px" height="150px"></a>
    </center>
</header>

ecommerce_project/templates/navbar.html
<nav class="navbar navbar-expand-lg" style="background-color:#b18363;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <li class="nav-item">
        <a class="nav-link" href="#">Borcelle</a>
      </li>
      <li class="nav-item dropdown {% if 'ecommerce_app' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Items
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'ecommerce_app:allProdCat' %}">All Products</a></li>
            {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
        </ul>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping" style="color: #463123;"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn" type="submit"><i class="fa-solid fa-magnifying-glass" style="color: #463123;"></i></button>
    </form>
  </div>
</nav>

ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

      {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} -  Borcelle

    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
  <div class="mx-auto">
    <p style="margin-left:120px;"><a href="{% url 'ecommerce_app:allProdCat' %}" style="text-decoration:none;color:black;">Home</a> | <a href="{{product.category.get_url}}" style="text-decoration:none;color:black;">{{product.category}}</a> | {{product.name}}</p>
  </div>
    <div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width:500px;height:380px;margin-bottom:10px">
        </div>
    </div>

        <div class="col-12 col-sm-12 col-md-12 col-lg-6" >
            <div style="margin-right:100px;">
         <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">products description</p>
            <p class="text-justify my_rod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out of stock</b></p>
            {% else %}
            <a  class="btn btn-secondary"  href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
            {% endif %}
           </div>
    </div>
</div>
        {% endblock %}
    </div>
</div>

ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

     we have variety of products.
{% endblock %}
{% block title %}
  search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b>"{{query}}"</b></p>
</div>
<div class="row mx_auto">
        {% for products in product %}
           <div class="my_bottom_margin col-9 col-sm-4 col-md-4 xol-lg-4">
           <div class="card text-center"  style="min-width:18rem;">
             <a href="{{products.get_url}}"><img class="card-img-top my_image" src="{{products.image.url}}" style="width:400px;height:350px;" alt="{{products.name}}"></a>
           <div class="card-body">
             <h4>{{products.name}}</h4>
             <p>{{products.price}}</p>
           </div>
           </div>
           </div>

{% empty %}
<div class="row mx-auto">
    <p class="text-center my_search_text"> 0 results found</p>
</div>
{% endfor %}
</div>
{% endblock %}